
site_name: HÃ¡lcova World Compendium
nav:
  - Planetary:
    - Planetary Parameters: halcova/planetary/planetary_parameters.md
    - Geography: halcova/planetary/geography.md
    - Flora and Fauna: halcova/planetary/flora_and_fauna.md
    - Atmosphere and Sky: halcova/planetary/atmosphere_and_sky.md
    - Lunar System: halcova/planetary/lunar_system.md
    - Climate History: halcova/planetary/climate_history.md
  - Metaphysics:
    - Metaphysical Spine: halcova/metaphysics/metaphysical_spine.md
    - Additional Systems: halcova/metaphysics/additional_systems.md
  - Magic Systems:
    - The Five Arts: halcova/magic/the_five_arts.md
  - Fate System:
     - Patterns and Bindings: halcova/fate_system/patterns_and_bindings.md
     - Echoes and Binding: halcova/fate_system/echoes_and_binding.md
     - Attunement and Marks: halcova/fate_system/attunement_and_marks.md
     - The Sorscad: halcova/fate_system/the_sorscad.md
     - The Loom: halcova/fate_system/the_loom.md
  - Governance:
    - Political Philosophy: halcova/governance/political_philosophy.md
    - Legal Frameworks: halcova/governance/legal_frameworks.md
    - Governance Structures: halcova/governance/governance_structures.md
    - Politics, Law, and Systems: halcova/governance/politics_law_and_systems.md
  - Society:
     - The Pattern Caste System: halcova/society/pattern_caste_system.md
     - Institutions and Roles: halcova/society/institutions_and_roles.md
     - Major Families: halcova/society/major_families.md
     - The Warden Order: halcova/society/the_warden_order.md
     - Religion: halcova/society/religion.md
     - Economics and Class: halcova/society/economics_and_class.md
     - Entertainment System: halcova/society/entertainment_system.md
     - Criminal Underworld: halcova/society/criminal_underworld.md
  - Conlang:
    - Language Set: halcova/conlang/language_set.md
    - Living Language Slang: halcova/conlang/living_language_slang.md
  - Halcova Stories:
    - The Reading: halcova/halcova_stories/01_the_reading_story_v3.md
    - Bleed: halcova/halcova_stories/02_bleed_story_v2.md
    - The Constrained: halcova/halcova_stories/03_the_constrained_story_v2.md
    - The Warden: halcova/halcova_stories/04_the_warden_story_v2.md
    - The Woven: halcova/halcova_stories/05_the_woven_story_v2.md


use_directory_urls: true
extra_css:
    - css/halcova-theme.css
